version: '3'
services:
  db-payments:
    image: 'postgres:alpine'
    volumes:
      - paymentsdb-volume:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: paymentsdb
      POSTGRES_HOST: postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  paymentsdb-volume:
