spring:
  application:
    name: ms-payments

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/paymentsdb}
    username: user
    password: 123456

  profiles:
    active: dev

  cloud:
    config:
      profile: dev

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest

server:
  port: ${SERVER_PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.int}
